#include "pch.h"
#include "SuiteSpot.h"
#include "SettingsUI.h"
#include "TrainingPackUI.h"
#include "UiJsonRenderer.h"
#include "LuaUiEngine.h"
#include <string>
#include <vector>
#include <fstream>
#include <filesystem>
#include <cctype>
#include <cstring>

namespace {
struct UiSnippet {
    const char* label;
    const char* code;
    const char* preview_id;
    const char* category;
};

struct UiValidatorRule {
    const char* token;
    const char* note;
};

static std::string ValidateImGui175(const char* text) {
    if (!text || text[0] == '\0') {
        return "Paste generated ImGui code above and click Validate.";
    }

    static const UiValidatorRule rules[] = {
        {"BeginTable", "Tables are not in ImGui 1.75. Use Columns() or BeginChild()."},
        {"TableSetupColumn", "Tables are not in ImGui 1.75. Use Columns() or BeginChild()."},
        {"TableNextRow", "Tables are not in ImGui 1.75. Use Columns() or BeginChild()."},
        {"TableNextColumn", "Tables are not in ImGui 1.75. Use Columns() or BeginChild()."},
        {"TableGetSortSpecs", "Tables are not in ImGui 1.75."},
        {"TableSetBgColor", "Tables are not in ImGui 1.75."},
        {"DockSpace", "Docking is not in ImGui 1.75 (master)."},
        {"DockBuilder", "Docking is not in ImGui 1.75 (master)."},
        {"Viewport", "Multi-viewport is not in ImGui 1.75 (master)."},
        {"Shortcut(", "ImGui::Shortcut() is newer than 1.75."},
        {"AddKeyEvent", "New input API is newer than 1.75."},
        {"AddMousePosEvent", "New input API is newer than 1.75."},
        {"AddMouseButtonEvent", "New input API is newer than 1.75."},
        {"AddMouseWheelEvent", "New input API is newer than 1.75."}
    };

    std::string src(text);
    std::string out;
    for (const auto& rule : rules) {
        if (src.find(rule.token) != std::string::npos) {
            out += "- ";
            out += rule.token;
            out += " : ";
            out += rule.note;
            out += "\n";
        }
    }
    if (out.empty()) {
        return "No known ImGui 1.75 incompatibilities found.";
    }
    return out;
}

static std::string BuildSnippetExport(const UiSnippet* snippets, size_t count) {
    std::string out;
    out += "// SuiteSpot ImGui 1.75 snippet pack\n";
    out += "// Generated by SuiteSpot UI Tools\n\n";
    for (size_t i = 0; i < count; ++i) {
        out += "// ---- ";
        out += snippets[i].label;
        out += "\n";
        out += snippets[i].code;
        if (!out.empty() && out.back() != '\n') {
            out += "\n";
        }
        out += "\n";
    }
    return out;
}
} // namespace

// #detailed comments: RenderSettings
// Purpose: Build the Settings UI using ImGui. This method is called on
// the UI thread and must complete quickly — avoid heavy computation
// or blocking calls here. Instead, schedule background work with
// gameWrapper->SetTimeout if needed.
//
// UI & state invariants:
//  - Any changes to cvars must keep the CVar<->member variable sync
//    consistent. The code uses cvarManager to persist values and also
//    updates plugin members; changing the order of writes may create
//    transient inconsistencies visible to users.
//  - Many UI controls guard against empty lists (e.g., RLTraining) and
//    clamp indices to valid ranges to prevent out-of-bounds access.
//
// DO NOT CHANGE: Rendering flow, label strings, and cvar names are
// relied upon by external automation and saved settings; altering them
// will change user-visible state persistence and CLI integrations.
void SuiteSpot::RenderSettings() {
    isRenderingSettings = true;
    // 1. Render the main settings UI
    if (settingsUI) {
        settingsUI->RenderMainSettingsWindow();
    }
    
    // 2. Render browser if open (Since RegisterDrawable is blocked)
    if (isBrowserOpen && trainingPackUI) {
        trainingPackUI->Render();
    }

    // 3. Dev-only UI tools (hidden unless suitespot_ui_editor is enabled)
    if (cvarManager) {
        auto editorCvar = cvarManager->getCvar("suitespot_ui_editor");
        if (editorCvar.getBoolValue()) {
            bool show_tools = true;
            bool show_demo = cvarManager->getCvar("suitespot_ui_show_demo").getBoolValue();
            bool show_metrics = cvarManager->getCvar("suitespot_ui_show_metrics").getBoolValue();
            bool show_style = cvarManager->getCvar("suitespot_ui_show_style").getBoolValue();

            if (ImGui::Begin("SuiteSpot UI Tools", &show_tools, ImGuiWindowFlags_AlwaysAutoResize)) {
                if (ImGui::Checkbox("Show ImGui Demo Window", &show_demo)) {
                    cvarManager->getCvar("suitespot_ui_show_demo").setValue(show_demo ? 1 : 0);
                }
                if (ImGui::Checkbox("Show ImGui Metrics Window", &show_metrics)) {
                    cvarManager->getCvar("suitespot_ui_show_metrics").setValue(show_metrics ? 1 : 0);
                }
                if (ImGui::Checkbox("Show ImGui Style Editor", &show_style)) {
                    cvarManager->getCvar("suitespot_ui_show_style").setValue(show_style ? 1 : 0);
                }
                ImGui::Separator();
                ImGui::TextDisabled("Dev-only tools. Set suitespot_ui_editor 0 to hide.");

                if (ImGui::CollapsingHeader("Widget Palette", ImGuiTreeNodeFlags_DefaultOpen)) {
                    static const UiSnippet snippets[] = {
                        {"Button", "if (ImGui::Button(\"Click Me\")) {\n    // TODO: action\n}\n", "##preview_button", "Buttons"},
                        {"SmallButton", "if (ImGui::SmallButton(\"Tiny\")) {\n    // TODO: action\n}\n", "##preview_smallbutton", "Buttons"},
                        {"Checkbox", "static bool enabled = false;\nImGui::Checkbox(\"Enable Feature\", &enabled);\n", "##preview_checkbox", "Inputs"},
                        {"Radio Buttons", "static int mode = 0;\nImGui::RadioButton(\"Mode A\", &mode, 0); ImGui::SameLine();\nImGui::RadioButton(\"Mode B\", &mode, 1);\n", "##preview_radio", "Inputs"},
                        {"Slider (int)", "static int value = 50;\nImGui::SliderInt(\"Value\", &value, 0, 100);\n", "##preview_slider_int", "Inputs"},
                        {"Slider (float)", "static float value = 0.5f;\nImGui::SliderFloat(\"Opacity\", &value, 0.0f, 1.0f);\n", "##preview_slider_float", "Inputs"},
                        {"Drag (float)", "static float speed = 1.0f;\nImGui::DragFloat(\"Speed\", &speed, 0.1f, 0.0f, 10.0f);\n", "##preview_drag_float", "Inputs"},
                        {"InputText", "static char buf[128] = \"\";\nImGui::InputText(\"Name\", buf, IM_ARRAYSIZE(buf));\n", "##preview_input_text", "Inputs"},
                        {"InputTextMultiline", "static char notes[512] = \"\";\nImGui::InputTextMultiline(\"Notes\", notes, IM_ARRAYSIZE(notes), ImVec2(0, 80));\n", "##preview_input_text_ml", "Inputs"},
                        {"Combo", "static int current = 0;\nconst char* items[] = {\"A\", \"B\", \"C\"};\nImGui::Combo(\"Mode\", &current, items, IM_ARRAYSIZE(items));\n", "##preview_combo", "Inputs"},
                        {"ListBox", "static int current = 0;\nconst char* items[] = {\"One\", \"Two\", \"Three\"};\nImGui::ListBox(\"Items\", &current, items, IM_ARRAYSIZE(items), 3);\n", "##preview_listbox", "Inputs"},
                        {"ColorEdit4", "static float color[4] = {1, 0, 0, 1};\nImGui::ColorEdit4(\"Tint\", color);\n", "##preview_color", "Inputs"},
                        {"CollapsingHeader", "if (ImGui::CollapsingHeader(\"Advanced\")) {\n    ImGui::Text(\"Details...\");\n}\n", "##preview_collapsing", "Layout"},
                        {"TreeNode", "if (ImGui::TreeNode(\"Group\")) {\n    ImGui::Text(\"Child item\");\n    ImGui::TreePop();\n}\n", "##preview_tree", "Layout"},
                        {"Tab Bar", "if (ImGui::BeginTabBar(\"Tabs\")) {\n    if (ImGui::BeginTabItem(\"One\")) {\n        ImGui::Text(\"Tab one\");\n        ImGui::EndTabItem();\n    }\n    if (ImGui::BeginTabItem(\"Two\")) {\n        ImGui::Text(\"Tab two\");\n        ImGui::EndTabItem();\n    }\n    ImGui::EndTabBar();\n}\n", "##preview_tabs", "Layout"},
                        {"BeginChild", "ImGui::BeginChild(\"Child\", ImVec2(0, 150), true);\nImGui::Text(\"Child content\");\nImGui::EndChild();\n", "##preview_child", "Layout"},
                        {"Tooltip", "ImGui::Text(\"Hover me\");\nif (ImGui::IsItemHovered()) {\n    ImGui::SetTooltip(\"Tooltip text\");\n}\n", "##preview_tooltip", "Advanced"},
                        {"Popup", "if (ImGui::Button(\"Open Popup\")) ImGui::OpenPopup(\"MyPopup\");\nif (ImGui::BeginPopup(\"MyPopup\")) {\n    ImGui::Text(\"Popup content\");\n    ImGui::EndPopup();\n}\n", "##preview_popup", "Advanced"},
                        {"Menu Bar", "if (ImGui::BeginMenuBar()) {\n    if (ImGui::BeginMenu(\"File\")) {\n        if (ImGui::MenuItem(\"Close\")) {}\n        ImGui::EndMenu();\n    }\n    ImGui::EndMenuBar();\n}\n", "##preview_menubar", "Advanced"},
                        {"Columns (legacy)", "ImGui::Columns(2, \"cols\", false);\nImGui::Text(\"Left\");\nImGui::NextColumn();\nImGui::Text(\"Right\");\nImGui::Columns(1);\n", "##preview_columns", "Layout"}
                    };
                    static const char* last_copied = "";
                    static std::string export_status;
                    static char filter_buf[128] = "";
                    static const UiSnippet* preview_snippet = nullptr;
                    static const char* categories[] = {"All", "Buttons", "Inputs", "Layout", "Advanced"};
                    static int category_idx = 0;
                    ImGui::Combo("Category", &category_idx, categories, IM_ARRAYSIZE(categories));
                    ImGui::InputText("Search", filter_buf, IM_ARRAYSIZE(filter_buf));
                    for (const auto& s : snippets) {
                        if (category_idx != 0 && strcmp(s.category, categories[category_idx]) != 0) {
                            continue;
                        }
                        if (filter_buf[0] != '\0') {
                            std::string needle(filter_buf);
                            std::string hay(s.label);
                            for (auto& ch : needle) ch = (char)tolower((unsigned char)ch);
                            for (auto& ch : hay) ch = (char)tolower((unsigned char)ch);
                            if (hay.find(needle) == std::string::npos) {
                                continue;
                            }
                        }
                        if (ImGui::Button(s.label)) {
                            ImGui::SetClipboardText(s.code);
                            last_copied = s.label;
                            preview_snippet = &s;
                        }
                        ImGui::SameLine();
                        if (ImGui::SmallButton("Preview")) {
                            preview_snippet = &s;
                        }
                    }
                    if (preview_snippet) {
                        ImGui::Separator();
                        ImGui::Text("Preview: %s", preview_snippet->label);
                        ImGui::BeginChild("SnippetPreview", ImVec2(0, 180), true);
                        if (strcmp(preview_snippet->preview_id, "##preview_button") == 0) {
                            ImGui::Button("Click Me");
                        } else if (strcmp(preview_snippet->preview_id, "##preview_smallbutton") == 0) {
                            ImGui::SmallButton("Tiny");
                        } else if (strcmp(preview_snippet->preview_id, "##preview_checkbox") == 0) {
                            static bool v = false;
                            ImGui::Checkbox("Enable Feature", &v);
                        } else if (strcmp(preview_snippet->preview_id, "##preview_radio") == 0) {
                            static int mode = 0;
                            ImGui::RadioButton("Mode A", &mode, 0); ImGui::SameLine();
                            ImGui::RadioButton("Mode B", &mode, 1);
                        } else if (strcmp(preview_snippet->preview_id, "##preview_slider_int") == 0) {
                            static int v = 50;
                            ImGui::SliderInt("Value", &v, 0, 100);
                        } else if (strcmp(preview_snippet->preview_id, "##preview_slider_float") == 0) {
                            static float v = 0.5f;
                            ImGui::SliderFloat("Opacity", &v, 0.0f, 1.0f);
                        } else if (strcmp(preview_snippet->preview_id, "##preview_drag_float") == 0) {
                            static float v = 1.0f;
                            ImGui::DragFloat("Speed", &v, 0.1f, 0.0f, 10.0f);
                        } else if (strcmp(preview_snippet->preview_id, "##preview_input_text") == 0) {
                            static char buf[128] = "";
                            ImGui::InputText("Name", buf, IM_ARRAYSIZE(buf));
                        } else if (strcmp(preview_snippet->preview_id, "##preview_input_text_ml") == 0) {
                            static char buf[512] = "";
                            ImGui::InputTextMultiline("Notes", buf, IM_ARRAYSIZE(buf), ImVec2(0, 60));
                        } else if (strcmp(preview_snippet->preview_id, "##preview_combo") == 0) {
                            static int current = 0;
                            const char* items[] = {"A", "B", "C"};
                            ImGui::Combo("Mode", &current, items, IM_ARRAYSIZE(items));
                        } else if (strcmp(preview_snippet->preview_id, "##preview_listbox") == 0) {
                            static int current = 0;
                            const char* items[] = {"One", "Two", "Three"};
                            ImGui::ListBox("Items", &current, items, IM_ARRAYSIZE(items), 3);
                        } else if (strcmp(preview_snippet->preview_id, "##preview_color") == 0) {
                            static float color[4] = {1, 0, 0, 1};
                            ImGui::ColorEdit4("Tint", color);
                        } else if (strcmp(preview_snippet->preview_id, "##preview_collapsing") == 0) {
                            if (ImGui::CollapsingHeader("Advanced")) {
                                ImGui::Text("Details...");
                            }
                        } else if (strcmp(preview_snippet->preview_id, "##preview_tree") == 0) {
                            if (ImGui::TreeNode("Group")) {
                                ImGui::Text("Child item");
                                ImGui::TreePop();
                            }
                        } else if (strcmp(preview_snippet->preview_id, "##preview_tabs") == 0) {
                            if (ImGui::BeginTabBar("Tabs")) {
                                if (ImGui::BeginTabItem("One")) {
                                    ImGui::Text("Tab one");
                                    ImGui::EndTabItem();
                                }
                                if (ImGui::BeginTabItem("Two")) {
                                    ImGui::Text("Tab two");
                                    ImGui::EndTabItem();
                                }
                                ImGui::EndTabBar();
                            }
                        } else if (strcmp(preview_snippet->preview_id, "##preview_child") == 0) {
                            ImGui::BeginChild("Child", ImVec2(0, 100), true);
                            ImGui::Text("Child content");
                            ImGui::EndChild();
                        } else if (strcmp(preview_snippet->preview_id, "##preview_tooltip") == 0) {
                            ImGui::Text("Hover me");
                            if (ImGui::IsItemHovered()) {
                                ImGui::SetTooltip("Tooltip text");
                            }
                        } else if (strcmp(preview_snippet->preview_id, "##preview_popup") == 0) {
                            if (ImGui::Button("Open Popup")) ImGui::OpenPopup("MyPopup");
                            if (ImGui::BeginPopup("MyPopup")) {
                                ImGui::Text("Popup content");
                                ImGui::EndPopup();
                            }
                        } else if (strcmp(preview_snippet->preview_id, "##preview_menubar") == 0) {
                            ImGui::BeginChild("MenuBarChild", ImVec2(0, 60), true, ImGuiWindowFlags_MenuBar);
                            if (ImGui::BeginMenuBar()) {
                                if (ImGui::BeginMenu("File")) {
                                    ImGui::MenuItem("Close");
                                    ImGui::EndMenu();
                                }
                                ImGui::EndMenuBar();
                            }
                            ImGui::EndChild();
                        } else if (strcmp(preview_snippet->preview_id, "##preview_columns") == 0) {
                            ImGui::Columns(2, "cols", false);
                            ImGui::Text("Left");
                            ImGui::NextColumn();
                            ImGui::Text("Right");
                            ImGui::Columns(1);
                        }
                        ImGui::EndChild();
                    }
                    if (ImGui::Button("Export snippets to file")) {
                        EnsureDataDirectories();
                        auto root = GetDataRoot();
                        if (!root.empty()) {
                            std::filesystem::path out_dir = root / "SuiteSpot" / "Dev";
                            std::error_code ec;
                            std::filesystem::create_directories(out_dir, ec);
                            std::filesystem::path out_path = out_dir / "ui_snippets.txt";
                            std::ofstream out_file(out_path, std::ios::binary | std::ios::trunc);
                            if (out_file) {
                                std::string content = BuildSnippetExport(snippets, IM_ARRAYSIZE(snippets));
                                out_file.write(content.data(), static_cast<std::streamsize>(content.size()));
                                export_status = std::string("Saved to: ") + out_path.string();
                            } else {
                                export_status = "Failed to write file. Check permissions.";
                            }
                        } else {
                            export_status = "Data root not available.";
                        }
                    }
                    if (last_copied[0] != '\0') {
                        ImGui::Text("Last copied: %s", last_copied);
                    }
                    if (!export_status.empty()) {
                        ImGui::TextWrapped("%s", export_status.c_str());
                    }
                }

                if (ImGui::CollapsingHeader("ImGui 1.75 Validator", ImGuiTreeNodeFlags_DefaultOpen)) {
                    static char code_buf[8192] = "";
                    static std::string validation_result;
                    ImGui::TextWrapped("Paste ImStudio-generated code here, then validate.");
                    ImGui::InputTextMultiline("##imgui_code", code_buf, IM_ARRAYSIZE(code_buf), ImVec2(500, 140));
                    if (ImGui::Button("Validate for ImGui 1.75")) {
                        validation_result = ValidateImGui175(code_buf);
                    }
                    if (!validation_result.empty()) {
                        ImGui::Separator();
                        ImGui::TextWrapped("%s", validation_result.c_str());
                    }
                }

                if (ImGui::CollapsingHeader("JSON UI (Experimental)", ImGuiTreeNodeFlags_DefaultOpen)) {
                    static UiJsonRenderer* json_renderer = nullptr;
                    if (!json_renderer) {
                        json_renderer = new UiJsonRenderer(this);
                    }

                    auto json_enable_cvar = cvarManager->getCvar("suitespot_ui_json_enable");
                    auto json_path_cvar = cvarManager->getCvar("suitespot_ui_json_path");
                    static char json_path_buf[260] = "";
                    static bool path_initialized = false;
                    if (!path_initialized) {
                        const std::string path_val = json_path_cvar.getStringValue();
                        strncpy_s(json_path_buf, path_val.c_str(), IM_ARRAYSIZE(json_path_buf) - 1);
                        path_initialized = true;
                    }

                    bool json_enabled = json_enable_cvar.getBoolValue();
                    if (ImGui::Checkbox("Render JSON UI", &json_enabled)) {
                        json_enable_cvar.setValue(json_enabled ? 1 : 0);
                    }
                    ImGui::InputText("JSON Path (relative to data root)", json_path_buf, IM_ARRAYSIZE(json_path_buf));
                    if (ImGui::Button("Save Path")) {
                        json_path_cvar.setValue(std::string(json_path_buf));
                    }
                    ImGui::SameLine();
                    if (ImGui::Button("Load/Reload JSON")) {
                        std::string err;
                        auto root = GetDataRoot();
                        std::filesystem::path path = std::filesystem::path(json_path_buf);
                        if (!path.is_absolute() && !root.empty()) {
                            path = root / path;
                        }
                        json_renderer->LoadFromFile(path, &err);
                    }
                    ImGui::SameLine();
                    if (ImGui::Button("Write Sample JSON")) {
                        EnsureDataDirectories();
                        auto root = GetDataRoot();
                        if (!root.empty()) {
                            std::filesystem::path out_path = root / "SuiteSpot" / "Dev" / "ui_layout.json";
                            std::error_code ec;
                            std::filesystem::create_directories(out_path.parent_path(), ec);
                            std::ofstream out(out_path, std::ios::binary | std::ios::trunc);
                            if (out) {
                                out <<
R"({
  "windows": [
    {
      "id": "demo_window",
      "title": "JSON UI Demo",
      "open": true,
      "flags": ["AlwaysAutoResize"],
      "widgets": [
        { "type": "text", "value": "Hello from JSON" },
        { "type": "separator" },
        { "type": "checkbox", "label": "Enable SuiteSpot", "bind_cvar": "suitespot_enabled" },
        { "type": "slider_int", "label": "Queue Delay", "bind_cvar": "suitespot_delay_queue_sec", "min": 0, "max": 300 },
        { "type": "combo", "label": "Map Type", "bind_cvar": "suitespot_map_type", "items": [0, 1, 2] },
        { "type": "button", "label": "Open Browser", "action": { "command": "togglemenu suitespot_browser" } }
      ]
    }
  ]
}
)";
                            }
                        }
                    }
                    if (!json_renderer->GetLastError().empty()) {
                        ImGui::TextWrapped("Last error: %s", json_renderer->GetLastError().c_str());
                    } else if (json_renderer->HasDocument()) {
                        ImGui::TextDisabled("Loaded: %s", json_renderer->GetLastPath().string().c_str());
                    }

                    if (json_enabled && json_renderer->HasDocument()) {
                        json_renderer->Render();
                    }
                }

                if (ImGui::CollapsingHeader("Lua UI (Experimental)", ImGuiTreeNodeFlags_DefaultOpen)) {
                    static LuaUiEngine* lua_engine = nullptr;
                    if (!lua_engine) {
                        lua_engine = new LuaUiEngine(this);
                    }

                    auto lua_enable_cvar = cvarManager->getCvar("suitespot_ui_lua_enable");
                    auto lua_path_cvar = cvarManager->getCvar("suitespot_ui_lua_path");
                    auto lua_autoreload_cvar = cvarManager->getCvar("suitespot_ui_lua_autoreload");
                    static char lua_path_buf[260] = "";
                    static bool lua_path_initialized = false;
                    if (!lua_path_initialized) {
                        const std::string path_val = lua_path_cvar.getStringValue();
                        strncpy_s(lua_path_buf, path_val.c_str(), IM_ARRAYSIZE(lua_path_buf) - 1);
                        lua_path_initialized = true;
                    }

                    bool lua_enabled = lua_enable_cvar.getBoolValue();
                    if (ImGui::Checkbox("Render Lua UI", &lua_enabled)) {
                        lua_enable_cvar.setValue(lua_enabled ? 1 : 0);
                    }
                    bool lua_autoreload = lua_autoreload_cvar.getBoolValue();
                    if (ImGui::Checkbox("Auto-reload Lua on change", &lua_autoreload)) {
                        lua_autoreload_cvar.setValue(lua_autoreload ? 1 : 0);
                    }
                    lua_engine->SetAutoReload(lua_autoreload);

                    ImGui::InputText("Lua Path (relative to data root)", lua_path_buf, IM_ARRAYSIZE(lua_path_buf));
                    if (ImGui::Button("Save Path")) {
                        lua_path_cvar.setValue(std::string(lua_path_buf));
                    }
                    ImGui::SameLine();
                    if (ImGui::Button("Load/Reload Lua")) {
                        std::string err;
                        auto root = GetDataRoot();
                        std::filesystem::path path = std::filesystem::path(lua_path_buf);
                        if (!path.is_absolute() && !root.empty()) {
                            path = root / path;
                        }
                        lua_engine->LoadFromFile(path, &err);
                    }
                    ImGui::SameLine();
                    if (ImGui::Button("Write Sample Lua")) {
                        EnsureDataDirectories();
                        auto root = GetDataRoot();
                        if (!root.empty()) {
                            std::filesystem::path out_path = root / "SuiteSpot" / "Dev" / "ui_layout.lua";
                            std::error_code ec;
                            std::filesystem::create_directories(out_path.parent_path(), ec);
                            std::ofstream out(out_path, std::ios::binary | std::ios::trunc);
                            if (out) {
                                out <<
R"(-- SuiteSpot Lua UI sample
local enabled = false
local counter = 0
local name = ""
local mode = 1
local items = {"Freeplay", "Training", "Workshop"}

function render()
  local open, visible = ui.begin_window("Lua UI Demo", true)
  if visible then
    ui.text("Hello from Lua")
    enabled = ui.checkbox("Enable SuiteSpot", enabled)
    counter, _ = ui.slider_int("Counter", counter, 0, 100)
    name, _ = ui.input_text("Name", name, 128)
    mode, _ = ui.combo("Map Type", items, mode)

    if ui.button("Open Browser") then
      cmd.exec("togglemenu suitespot_browser")
    end
  end
  ui.end_window()
end
)";
                            }
                        }
                    }

                    if (!lua_engine->GetLastError().empty()) {
                        ImGui::TextWrapped("Last error: %s", lua_engine->GetLastError().c_str());
                    } else if (lua_engine->HasScript()) {
                        ImGui::TextDisabled("Loaded: %s", lua_engine->GetLastPath().string().c_str());
                    }

                    if (lua_enabled && lua_engine->HasScript()) {
                        lua_engine->Render();
                    }
                }
            }
            ImGui::End();

            if (!show_tools) {
                editorCvar.setValue(0);
            }

            if (show_demo) {
                ImGui::ShowDemoWindow(&show_demo);
                if (!show_demo) {
                    cvarManager->getCvar("suitespot_ui_show_demo").setValue(0);
                }
            }
            if (show_metrics) {
                ImGui::ShowMetricsWindow(&show_metrics);
                if (!show_metrics) {
                    cvarManager->getCvar("suitespot_ui_show_metrics").setValue(0);
                }
            }
            if (show_style) {
                if (ImGui::Begin("ImGui Style Editor", &show_style)) {
                    ImGui::ShowStyleEditor();
                }
                ImGui::End();
                if (!show_style) {
                    cvarManager->getCvar("suitespot_ui_show_style").setValue(0);
                }
            }
        }
    }
    isRenderingSettings = false;
}
